config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  get "blog_post/new" => "blog_posts#new", as: :new_blog_post
  get "blog_post/:id/edit" => "blog_posts#edit", as: :edit_blog_post
  patch "blog_post/:id" => "blog_posts#update"
  delete "blog_post/:id" => "blog_posts#destroy"
  get "blog_post/:id" => "blog_posts#show", as: :blog_post
  post "blog_post" => "blog_posts#create", as: :blog_posts

  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blog_posts = BlogPost.all
  end

  def show
    @blog_post = BlogPost.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render file: Rails.root.join("public", "404.html"), status: :not_found
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    if @blog_post.save
        redirect_to @blog_post, notice: 'Blog post was successfully created.'
    else
        render :new, :status => :unprocessable_entity
    end
  end

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def update
    @blog_post = BlogPost.find(params[:id])
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post, notice: 'Blog post was successfully updated.'
    else
      render :edit, :status => :unprocessable_entity
    end
  end

  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy
    redirect_to root_path, notice: 'Blog post was successfully destroyed.'
  end

  private
    def blog_post_params
      params.require(:blog_post).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
    </div>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <%= form.button %>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/index.html.erb
<h1>All Blog Posts</h1>

<%= button_to "New Post", new_blog_post_path %>

<% @blog_posts.each do |post| %>
    <div class="blog-post">
        <h2><%= link_to post.title, post %></h2>
        <p><%= post.body %></p>
    </div>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<h1><%= @blog_post.title %></h1>
<p><%= @blog_post.body %></p>
<p><em>Posted on <%= @blog_post.created_at.strftime("%B %d, %Y") %></em></p>
<p><%= link_to "Back to all posts", "/" %></p>
<br>
<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>